export const editorControls = [{
    label: 'Brightness',
    prop: 'brightness',
    min: 0,
    max: 5,
    step: 0.1,
    value: 1,
    unit: ''
  }, {
    label: 'Grayscale',
    prop: 'grayscale',
    min: 0,
    max: 1,
    step: 0.1,
    value: 0,
    unit: ''
  }, {
    label: 'Saturate',
    prop: 'Saturate',
    min: 0,
    max: 5,
    step: 0.1,
    value: 1,
    unit: ''
  }, {
    label: 'Sepia',
    prop: 'sepia',
    min: 0,
    max: 1,
    step: 0.1,
    value: 0,
    unit: ''
  },{
    label: 'Contrast',
    prop: 'contrast',
    min: 0,
    step: 0.1,
    max: 1,
    value: 1,
    unit: ''
  }, {
    label: 'Hue rotate',
    prop: 'hue-rotate',
    min: 0,
    step: 1,
    max: 360,
    value: 1,
    unit: 'deg'
  },{
    label: 'Invert',
    prop: 'invert',
    min: 0,
    step: 0.1,
    max: 1,
    value: 0,
    unit: ''
  }, {
    label: 'Blur',
    prop: 'blur',
    min: 0,
    max: 5,
    step: 0.02,
    value: 0,
    unit: 'px'
  }]